export const INCREASE = "INCREASE"
export const DECREASE = "DECREASE"
export const CLEAR    = "CLEAR"
export const REMOVE   = "REMOVE"
export const GET_TOTALS = "GET_TOTALS"
export const TOGGLE_AMOUNT = "TOGGLE_AMOUNT"
