export const INCREASE = "INCREASE"
export const DECREASE = "DECREASE"
export const CLEAR    = "CLEAR"
export const REMOVE   = "REMOVE"
export const GET_TOTALS = "GET_TOTALS"
export const NUM_OF_ITEMS = "NUM_OF_ITEMS"